logging:
  level: error
  level.org.springframework.data: debug

# Database or in-memory implementation
service:
  class: InMemory
#  class: H2Service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    password: 40PdyLX3pm
    url: jdbc:h2:mem:widget_db;
    username: miro
    driver-class-name: org.h2.Driver
    platform: h2
    schema-password: dU6qVPAhAqQT3GJHFXgcyEYXq44qwC
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    show-sql: true


#Config for rate limits of endpoints
zuul:
  routes:
    widgetsAll:
      path: /api/v1/widgets
      url: forward:/
    default:
      strip-prefix: false
      path: /api/v1/widgets/**
      url: forward:/
  ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      widgetsAll:
        - limit: 200
          refresh-interval: 60
          type:
            - origin
      default:
        - limit: 1000
          refresh-interval: 60
          type:
            - origin
  strip-prefix: true