logging:
  level: error
  level.org.springframework.data: debug

server:
  port: 8081


management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    password: 40PdyLX3pm
    url: jdbc:h2:mem:widget_db;
    username: miro
    driver-class-name: org.h2.Driver
    platform: postgresql
    schema-password: dU6qVPAhAqQT3GJHFXgcyEYXq44qwC
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    show-sql: true

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      filter-method: servlet
      filter-order: -10
      url: .*
      metrics:
        tags:
          - key: USERNAME
            expression: "'anonym'"
          - key: URL
            expression: getRequestURI()
      rate-limits:
        - bandwidths:
            - capacity: 30
              time: 1
              unit: minutes